[tool.poetry]
name = "venv"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "==3.11.2"
scikit-learn = "^1.2.2"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
seaborn = "^0.12.2"
termcolor = "^2.3.0"
django = "^4.2"
djangorestframework = "^3.14.0"
markdown = "^3.4.3"
django-filter = "^23.1"
numpy = "^1.24.3"
pandas = "^2.0.1"
statsmodels = "^0.13.5"
xgboost = "^1.7.5"
django-cors-headers = "^3.14.0"
requests = "^2.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
