# Generated by Django 4.2 on 2023-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_file', '0002_miscdata_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscdata',
            name='parent_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
